- color: c96144
  description: Contains breaking changes
  name: breaking
- color: d73a4a
  description: Something isn't working
  name: bug
- color: 0075ca
  description: Improvements or additions to documentation
  name: documentation
- color: cfd3d7
  description: This issue or pull request already exists
  name: duplicate
- color: a2eeef
  description: New feature or request
  name: enhancement
- color: 7057ff
  description: Good for newcomers
  name: good first issue
- color: "008672"
  description: Extra attention is needed
  name: help wanted
- color: "8befb1"
  description: This issue or pull request needs a review
  name: needs review
- color: "e4e669"
  description: This doesn't seem right
  name: invalid
- color: "e2737b"
  description: This issue is a proposal, usually non-trivial change
  name: proposal
- color: "d876e3"
  description: Further information is requested
  name: question
- color: "f9d0c4"
  description: Changelog generator release summary
- color: "0366d6"
  description: Contains dependencies changes
  name: dependencies
- color: "4aacf7"
  description: Contains a internal change this is not observable by users.
  name: chore
- color: "480b82"
  description: Contains security related changes
  name: security
- color: "ffffff"
  description: This will not be worked on
  name: wontfix
